# Generated by Django 4.2.4 on 2023-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('prio', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
